name: Spring Boot CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: ソース取得
        uses: actions/checkout@v4

      - name: javaセットアップ
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Gradle権限付与
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew build

      - name: テストレポート保存
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: build/reports/tests/test
